# Generated by Django 6.0 on 2026-01-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_championshipstanding'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_score1', models.IntegerField(blank=True, null=True)),
                ('old_score2', models.IntegerField(blank=True, null=True)),
                ('new_score1', models.IntegerField(blank=True, null=True)),
                ('new_score2', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.match')),
            ],
        ),
    ]
