# Generated by Django 6.0 on 2026-01-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_matchaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
