# Generated by Django 6.0 on 2026-01-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_match_loser_match_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPodium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('bronze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronze_events', to='tournament.team')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.event')),
                ('gold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_events', to='tournament.team')),
                ('silver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_events', to='tournament.team')),
            ],
        ),
    ]
