# Generated by Django 6.0 on 2026-01-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_eventpodium'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
