# Generated by Django 6.0 on 2026-01-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_event_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeGroupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('summary', models.CharField(help_text='Optional summary (IMP total, boards played, etc.)', max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.event')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.team')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.team')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tournament.team')),
            ],
            options={
                'unique_together': {('event', 'group')},
            },
        ),
    ]
