# Generated by Django 6.0 on 2026-01-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_bridgegroupresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1_players',
            field=models.CharField(blank=True, help_text='Names of players for Team 1', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_players',
            field=models.CharField(blank=True, help_text='Names of players for Team 2', max_length=200, null=True),
        ),
    ]
