# Generated by Django 6.0 on 2026-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_match_team1_players_match_team2_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owners',
            field=models.CharField(blank=True, help_text='Comma-separated names of team owners', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_players',
            field=models.CharField(blank=True, help_text='Actual players for this match', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_players',
            field=models.CharField(blank=True, help_text='Actual players for this match', max_length=600, null=True),
        ),
    ]
