# Generated by Django 6.0 on 2026-01-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_team_owners_alter_match_team1_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchaudit',
            name='match',
        ),
        migrations.AlterUniqueTogether(
            name='bridgegroupresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bridgegroupresult',
            name='group',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_players',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_players',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='owners',
            field=models.CharField(blank=True, help_text='Team Owners', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='SwimmingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.event')),
                ('fifth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_5th', to='tournament.team')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_1st', to='tournament.team')),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_4th', to='tournament.team')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_2nd', to='tournament.team')),
                ('sixth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_6th', to='tournament.team')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_3rd', to='tournament.team')),
            ],
        ),
        migrations.DeleteModel(
            name='EventPodium',
        ),
        migrations.DeleteModel(
            name='MatchAudit',
        ),
        migrations.RemoveField(
            model_name='bridgegroupresult',
            name='summary',
        ),
    ]
