# Generated by Django 6.0 on 2026-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_matchaudit_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pool',
            field=models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], default='A', max_length=1),
        ),
    ]
