# Generated by Django 6.0 on 2026-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_team_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sport_label',
            field=models.CharField(blank=True, help_text='Assigned sport category from roster sheet', max_length=100, null=True),
        ),
    ]
