# Generated by Django 6.0 on 2026-01-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_team_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='team_icons/'),
        ),
    ]
