# Generated by Django 6.0 on 2026-01-07 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_event_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgegroupresult',
            name='first_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bridgegroupresult',
            name='second_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='bridgegroupresult',
            name='third_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bridgegroupresult',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_first', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='bridgegroupresult',
            name='second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_second', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='bridgegroupresult',
            name='third',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_third', to='tournament.team'),
        ),
    ]
