# Generated by Django 6.0.1 on 2026-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_bridgegroupresult_first_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(unique=True)),
                ('event_name', models.CharField(max_length=100)),
                ('results_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['event_id'],
            },
        ),
    ]
