# Generated by Django 6.0.1 on 2026-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0017_manualeventresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshipstanding',
            name='penalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
