# Generated by Django 6.0.1 on 2026-01-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_championshipstanding_penalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshipstanding',
            name='gross_total',
            field=models.IntegerField(default=0),
        ),
    ]
