# Generated by Django 6.0.1 on 2026-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0019_championshipstanding_gross_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshipstanding',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
